services:
    api:
        container_name: api
        build:
          context: .
          dockerfile: ./Sales.WebApi/Dockerfile
        depends_on:
          postgres:
            condition: service_started
        restart: always
        networks:
          - backend
        ports:
          - 5000:80

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        ports:
          - 5432:5432
        networks:
          - backend
        volumes:
          - postgres-data:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shopping_center

    migrations:
        container_name: migrations
        build:
          context: .
          dockerfile: ./Gateways/Dockerfile
        networks:
          - backend
        restart: on-failure:5
        depends_on:
          postgres:
            condition: service_started
        

volumes:
  postgres-data:

networks:
  backend:
    name: backend